services:
  notification-db:
    image: postgres:15
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  notification-service:
    build: .
    ports:
      - "8005:8000"
    env_file:
      - .env
    depends_on:
      - notification-db
      - redis

volumes:
  notification-db-data:
