services:
  product_db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: karis
      POSTGRES_PASSWORD: karis
      SW: ${sw}
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postresql/data

  product-service:
    build: ../services/product-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - product-db

  volumes:
    product-db-data:
