services:
  payment-db:
    image: postgres:15
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  payment-service:
    build: .
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - payment-db

volumes:
  payment-db-data:
