services:
  order-db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: kariuki
      POSTGRES_PASSWORD: karis
    ports:
      - "5432:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  order-service:
    build: ../services/order-service
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - order-db

volumes:
  order-db-data
