services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: kariuki
      POSTGRES_PASSWORD: karis
      SW: ${sw}
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    build: ../services/auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - auth-db

volumes:
  auth-db-data:
